openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/signup:
    post:
      summary: 'User Registration'
      operationId: userRegistration
      description: ''
      parameters: []
      responses:
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: false
                  status_code: 400
                  message: 'The confirm password field must match password.'
                  errors:
                    confirm_password:
                      - 'The confirm password field must match password.'
                  data: []
                properties:
                  status:
                    type: boolean
                    example: false
                  status_code:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: 'The confirm password field must match password.'
                  errors:
                    type: object
                    properties:
                      confirm_password:
                        type: array
                        example:
                          - 'The confirm password field must match password.'
                        items:
                          type: string
                  data:
                    type: array
                    example: []
      tags:
        - 'Auth routes'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: pxftcndcmfjvsfytfmy
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: jacquelyn.crist@example.net
                password:
                  type: string
                  description: 'Must be at least 6 characters. Must not be greater than 255 characters.'
                  example: "'t|z*{>nk<;{d.>1b~5"
                confirm_password:
                  type: string
                  description: 'The value and <code>password</code> must match.'
                  example: sint
              required:
                - name
                - email
                - password
                - confirm_password
      security: []
  /api/login:
    post:
      summary: Login
      operationId: login
      description: ''
      parameters: []
      responses:
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: false
                  status_code: 400
                  message: 'The selected email is invalid.'
                  errors:
                    email:
                      - 'The selected email is invalid.'
                  data: []
                properties:
                  status:
                    type: boolean
                    example: false
                  status_code:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: 'The selected email is invalid.'
                  errors:
                    type: object
                    properties:
                      email:
                        type: array
                        example:
                          - 'The selected email is invalid.'
                        items:
                          type: string
                  data:
                    type: array
                    example: []
      tags:
        - 'Auth routes'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: viviane.vandervort@example.org
                password:
                  type: string
                  description: 'Must be at least 6 characters.'
                  example: 'y3ozM$6[lEO{0hN,'
              required:
                - email
                - password
      security: []
  /api/profile/data:
    get:
      summary: 'Get Profile Data'
      operationId: getProfileData
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: true
                  status_code: 200
                  message: ''
                  data:
                    id: ac49ffdc-8568-481c-8587-5cb3f846af5f
                    name: 'test update'
                    email: hassanshahriar18@gmail.com
                    user_type: User
                    login_type: default
                    dob: '2022-01-01'
                    phone: '11111111111'
                    created_at: '2023-05-11T07:16:47.000000Z'
                    updated_at: '2023-05-15T11:05:59.000000Z'
                    deleted_at: null
                properties:
                  status:
                    type: boolean
                    example: true
                  status_code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: ''
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: ac49ffdc-8568-481c-8587-5cb3f846af5f
                      name:
                        type: string
                        example: 'test update'
                      email:
                        type: string
                        example: hassanshahriar18@gmail.com
                      user_type:
                        type: string
                        example: User
                      login_type:
                        type: string
                        example: default
                      dob:
                        type: string
                        example: '2022-01-01'
                      phone:
                        type: string
                        example: '11111111111'
                      created_at:
                        type: string
                        example: '2023-05-11T07:16:47.000000Z'
                      updated_at:
                        type: string
                        example: '2023-05-15T11:05:59.000000Z'
                      deleted_at:
                        type: string
                        example: null
      tags:
        - Profile
  /api/profile/update:
    post:
      summary: 'Update Profile'
      operationId: updateProfile
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: false
                  status_code: 400
                  message: 'The selected id is invalid.'
                  errors:
                    id:
                      - 'The selected id is invalid.'
                  data: []
                properties:
                  status:
                    type: boolean
                    example: false
                  status_code:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: 'The selected id is invalid.'
                  errors:
                    type: object
                    properties:
                      id:
                        type: array
                        example:
                          - 'The selected id is invalid.'
                        items:
                          type: string
                  data:
                    type: array
                    example: []
      tags:
        - Profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: ''
                  example: ab
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: aemx
                dob:
                  type: string
                  description: 'Must be a valid date in the format <code>Y-m-d</code>.'
                  example: '2023-05-15'
                phone:
                  type: string
                  description: 'Must be 11 characters.'
                  example: fwngtymxyyp
              required:
                - id
                - name
  /api/reset-password-link:
    post:
      summary: 'Sending reset password link'
      operationId: sendingResetPasswordLink
      description: ''
      parameters: []
      responses:
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: false
                  status_code: 400
                  message: 'The selected email is invalid.'
                  errors:
                    email:
                      - 'The selected email is invalid.'
                  data: []
                properties:
                  status:
                    type: boolean
                    example: false
                  status_code:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: 'The selected email is invalid.'
                  errors:
                    type: object
                    properties:
                      email:
                        type: array
                        example:
                          - 'The selected email is invalid.'
                        items:
                          type: string
                  data:
                    type: array
                    example: []
      tags:
        - 'Reset password'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: tanner76@example.org
              required:
                - email
      security: []
  /api/reset-password:
    post:
      summary: 'Password reset'
      operationId: passwordReset
      description: ''
      parameters: []
      responses:
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: false
                  status_code: 400
                  message: 'The selected email is invalid.'
                  errors:
                    email:
                      - 'The selected email is invalid.'
                  data: []
                properties:
                  status:
                    type: boolean
                    example: false
                  status_code:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: 'The selected email is invalid.'
                  errors:
                    type: object
                    properties:
                      email:
                        type: array
                        example:
                          - 'The selected email is invalid.'
                        items:
                          type: string
                  data:
                    type: array
                    example: []
      tags:
        - 'Reset password'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: ''
                  example: architecto
                password:
                  type: string
                  description: 'Must be at least 6 characters.'
                  example: 'r2/''w>\[IE'
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: taylor.yundt@example.net
              required:
                - token
                - password
                - email
      security: []
  /api/resume/contact:
    post:
      summary: 'create or update contact'
      operationId: createOrUpdateContact
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: false
                  status_code: 400
                  message: 'The selected id is invalid.'
                  errors:
                    id:
                      - 'The selected id is invalid.'
                  data: []
                properties:
                  status:
                    type: boolean
                    example: false
                  status_code:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: 'The selected id is invalid.'
                  errors:
                    type: object
                    properties:
                      id:
                        type: array
                        example:
                          - 'The selected id is invalid.'
                        items:
                          type: string
                  data:
                    type: array
                    example: []
      tags:
        - Resume
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: ''
                  example: quis
                first_name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: xvqwpkqkmtc
                last_name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: adcmzniyqjdvudrrmeuzoenl
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: tad69@example.com
                job_title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: ywwmeiczfvcwfvecoszplr
                phone:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: xluk
                location:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: oxjsswvlvcyz
                linkedin_link:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: iakiewygrvevx
                facebook_link:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: zls
                twitter_link:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: eeqxufneitxdplwfgqdqrkf
                website:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: spacjzoehnibwgm
              required:
                - id
                - first_name
                - last_name
                - email
                - job_title
                - phone
                - location
  /api/resume/education:
    post:
      summary: 'create or update education'
      operationId: createOrUpdateEducation
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: true
                  status_code: 200
                  message: ''
                  data:
                    name: xyulimtsneqqxgrldl
                    school_name: puelwxzjtberosedwtvycue
                    location: xfdmhiglivsh
                    feild_of_study: fg
                    start_date: '2023-05-15'
                    active: true
                    end_date: '2023-05-15'
                    user_id: ac49ffdc-8568-481c-8587-5cb3f846af5f
                    id: 97aafdf4-7f89-4318-9ad9-24cedfaeb2fe
                    updated_at: '2023-05-15T16:32:40.000000Z'
                    created_at: '2023-05-15T16:32:40.000000Z'
                properties:
                  status:
                    type: boolean
                    example: true
                  status_code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: ''
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                        example: xyulimtsneqqxgrldl
                      school_name:
                        type: string
                        example: puelwxzjtberosedwtvycue
                      location:
                        type: string
                        example: xfdmhiglivsh
                      feild_of_study:
                        type: string
                        example: fg
                      start_date:
                        type: string
                        example: '2023-05-15'
                      active:
                        type: boolean
                        example: true
                      end_date:
                        type: string
                        example: '2023-05-15'
                      user_id:
                        type: string
                        example: ac49ffdc-8568-481c-8587-5cb3f846af5f
                      id:
                        type: string
                        example: 97aafdf4-7f89-4318-9ad9-24cedfaeb2fe
                      updated_at:
                        type: string
                        example: '2023-05-15T16:32:40.000000Z'
                      created_at:
                        type: string
                        example: '2023-05-15T16:32:40.000000Z'
      tags:
        - Resume
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: ''
                  example: null
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: xyulimtsneqqxgrldl
                school_name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: puelwxzjtberosedwtvycue
                location:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: xfdmhiglivsh
                feild_of_study:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: fg
                start_date:
                  type: string
                  description: 'Must be a valid date in the format <code>Y-m-d</code>.'
                  example: '2023-05-15'
                active:
                  type: boolean
                  description: ''
                  example: true
                end_date:
                  type: string
                  description: 'Must be a valid date in the format <code>Y-m-d</code>. This field is required when <code>active</code> is <code>true</code>.'
                  example: '2023-05-15'
              required:
                - name
                - school_name
                - start_date
                - active
  /api/resume/skill:
    post:
      summary: 'Skills create or update'
      operationId: skillsCreateOrUpdate
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: false
                  status_code: 400
                  message: 'The skills.0.name field is required.'
                  errors:
                    skills.0.name:
                      - 'The skills.0.name field is required.'
                  data: []
                properties:
                  status:
                    type: boolean
                    example: false
                  status_code:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: 'The skills.0.name field is required.'
                  errors:
                    type: object
                    properties:
                      skills.0.name:
                        type: array
                        example:
                          - 'The skills.0.name field is required.'
                        items:
                          type: string
                  data:
                    type: array
                    example: []
      tags:
        - Resume
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                skills:
                  type: array
                  description: ''
                  example:
                    - voluptatibus
                  items:
                    type: string
  '/api/resume/skill/{skill_id}':
    delete:
      summary: 'Delete skill'
      operationId: deleteSkill
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses: {  }
      tags:
        - Resume
    parameters:
      -
        in: path
        name: skill_id
        description: 'The ID of the skill.'
        example: voluptatum
        required: true
        schema:
          type: string
  /api/resume/objective:
    post:
      summary: 'create or update objective'
      operationId: createOrUpdateObjective
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        400:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: false
                  status_code: 400
                  message: 'Already created data please update your data, if you want any modification'
                  data: []
                properties:
                  status:
                    type: boolean
                    example: false
                  status_code:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: 'Already created data please update your data, if you want any modification'
                  data:
                    type: array
                    example: []
      tags:
        - Resume
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: ''
                  example: null
                details:
                  type: string
                  description: 'Must be at least 20 characters.'
                  example: zrtrajzxkydyvwrlzkysinhvgzydascffuzrosnkncwzeugdfrktuxyusmxfczevlrvquxkdeynldhzanjnvkymuc
              required:
                - details
  /api/resume/project:
    post:
      summary: 'create or update project'
      operationId: createOrUpdateProject
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: true
                  status_code: 200
                  message: ''
                  data:
                    id: 3f04fe59-5d5d-4dac-aeaa-43814a41e2cc
                    title: skpsrimlz
                    role: nmdw
                    start_date: '2023-05-15'
                    end_date: '2023-05-15'
                    details: vvoesyygrbuhjgdxwksnofmdkaqyywainnorbwhaykujgboteoonqbtebjegfvddzchgdiumvkzhofmvx
                properties:
                  status:
                    type: boolean
                    example: true
                  status_code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: ''
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: 3f04fe59-5d5d-4dac-aeaa-43814a41e2cc
                      title:
                        type: string
                        example: skpsrimlz
                      role:
                        type: string
                        example: nmdw
                      start_date:
                        type: string
                        example: '2023-05-15'
                      end_date:
                        type: string
                        example: '2023-05-15'
                      details:
                        type: string
                        example: vvoesyygrbuhjgdxwksnofmdkaqyywainnorbwhaykujgboteoonqbtebjegfvddzchgdiumvkzhofmvx
      tags:
        - Resume
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: ''
                  example: null
                title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: skpsrimlz
                role:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: nmdw
                start_date:
                  type: string
                  description: 'Must be a valid date in the format <code>Y-m-d</code>.'
                  example: '2023-05-15'
                end_date:
                  type: string
                  description: 'Must be a valid date in the format <code>Y-m-d</code>.'
                  example: '2023-05-15'
                details:
                  type: string
                  description: 'Must be at least 10 characters.'
                  example: vvoesyygrbuhjgdxwksnofmdkaqyywainnorbwhaykujgboteoonqbtebjegfvddzchgdiumvkzhofmvx
              required:
                - title
                - details
  '/api/resume/project/{project_id}':
    delete:
      summary: 'Delete project'
      operationId: deleteProject
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses: {  }
      tags:
        - Resume
    parameters:
      -
        in: path
        name: project_id
        description: 'The ID of the project.'
        example: sequi
        required: true
        schema:
          type: string
tags:
  -
    name: 'Auth routes'
    description: ''
  -
    name: Profile
    description: ''
  -
    name: 'Reset password'
    description: ''
  -
    name: Resume
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
